# Generated by Django 5.0.3 on 2024-04-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='totalPrice',
            new_name='total_price',
        ),
    ]
