# Generated by Django 5.0.3 on 2025-12-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedreceipt',
            name='merchant',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='importedreceipt',
            name='merchantAddress',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='interpretation',
            name='provider',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lineitemmodel',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lineitemmodel',
            name='product',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lineitemmodel',
            name='quantityUnit',
            field=models.CharField(max_length=250),
        ),
    ]
