# Generated by Django 5.0.3 on 2025-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_importedreceipt_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedreceipt',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='importedreceipt',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='importedreceipt',
            name='merchant',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='importedreceipt',
            name='merchantAddress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
