# Generated by Django 5.0.3 on 2025-12-27 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_importedreceipt_currency_importedreceipt_totalprice_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItemModel',
            new_name='ImportedLineItemModel',
        ),
    ]
