# Generated by Django 5.0.3 on 2025-12-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_lineitemmodel_importedlineitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedlineitemmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='importedlineitemmodel',
            name='product',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='importedlineitemmodel',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='importedlineitemmodel',
            name='quantityUnit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='importedlineitemmodel',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
