# Generated by Django 5.0.3 on 2024-06-22 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_store_brand_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=3, default=1, max_digits=7)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'l'), ('cl', 'cl'), ('dl', 'dl'), ('ml', 'ml'), ('m', 'm'), ('cm', 'cm'), ('sqm', 'sqm'), ('pcs', 'pcs')], default='pcs', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.productsize'),
        ),
    ]
