# Generated by Django 5.0.3 on 2025-12-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_importedlineitemmodel_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interpretation',
            new_name='Upload',
        ),
    ]
