# Generated by Django 5.0.3 on 2024-12-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_receipt_analyzed_alter_receipt_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedStoreAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.store')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyzed_result', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.receipt')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.analyzedstorealias')),
            ],
        ),
    ]
