# Generated by Django 5.0.3 on 2024-12-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_analyzedreceipt_analyzed_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedreceipt',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_receipt', to='app.receipt'),
        ),
    ]
