# Generated by Django 5.0.3 on 2024-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_analyzedreceipt_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedreceipt',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
