# Generated by Django 5.0.3 on 2024-12-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_analyzedreceipt_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedreceipt',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
