# Generated by Django 5.0.3 on 2024-12-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_analyzedreceipt_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateTimeField(blank=True, db_column='date', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='store',
            field=models.ForeignKey(blank=True, db_column='store', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.store'),
        ),
    ]
