# Generated by Django 5.0.3 on 2024-04-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_brand_store_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.brand'),
        ),
    ]
