---
- name: Deploy to production
  hosts:
    - boutique
  gather_facts: no
  vars:
    container_name: boutique
    project_dir: "/srv/boutique"
    environment:
      DJANGO_DEBUG: True
      SECRET_KEY: "django-insecure-lwyh*yitd$0=k3uo2)oiqz6()yqi4d9t9l-u!1#&caz6l43tfh"
      ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://*:*"
      MEDIA_ROOT: "/app/uploads/"
      DB_NAME: "/db/db.sqlite3"
  tasks:
    - name: Create the env file
      ansible.builtin.template:
        src: env.j2
        dest: "{{ project_dir }}/.env"
    - name: Ensure database file exists
      ansible.builtin.file:
        path: "{{ project_dir }}/db.sqlite3"
        state: touch
    - name: Create container with new image
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: ghcr.io/darthmikke/boutique
        volumes:
          - "{{ project_dir }}/.env:/app/.env"
          - "{{ project_dir }}/db.sqlite3:{{ environment.DB_NAME }}"
          - "{{ project_dir }}/public:/app/public"
        restart_policy: always
        state: stopped
        detach: true
    - name: Migrate
      community.docker.docker_container_exec:
        name: "{{ container_name }}"
        command: migrate
    - name: Ensure a superuser exists
      community.docker.docker_container_exec:
        name: "{{ container_name }}"
        command: createsuperuser --username admin --email admin@example.com --noinput
        environment:
          - DJANGO_SUPERUSER_PASSWORD="password1234"
    - name: Copy static files
      community.docker.docker_container_exec:
        name: "{{ container_name }}"
        command: collectstatic
    - name: Start the app
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: started
